/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mava_MysqlConn;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;


/**
 *
 * @author sumit
 */
public class Mava_MysqlConn extends javax.swing.JFrame {

   private static final String username = "root";
   private static final String password = "Sumit@8221";
   private static final String dataconn = "jdbc:mysql://localhost:3306/connector";
   int q,i,id,deleteItem;
   
   
   Connection sqlConn = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   
    public Mava_MysqlConn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //===============================FUNCTION================================//
    //"com.mysql.jdbc.Driver"
    public void upDateDB()
    {
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataconn,username,password);
            pst = sqlConn.prepareStatement("select * from connector");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
                    RecordTable.setRowCount(0);
                    
                    while(rs.next()){
                        Vector columnData = new Vector();
                        
                        for(i = 1;i <= q;i++)
                        {
                            columnData.add(rs.getString("id"));
                            columnData.add(rs.getString("StudentID"));
                            columnData.add(rs.getString("FirstName"));
                            columnData.add(rs.getString("Surname"));
                            columnData.add(rs.getString("Address"));
                            columnData.add(rs.getString("PostCode"));
                            columnData.add(rs.getString("TelePhone")); 
                        }
                        RecordTable.addRow(columnData);
                    }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    //===============================END FUNCTION============================//
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnAddnew = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxtStudentid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtTelephone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtPostcode = new javax.swing.JLabel();
        jtxtPostCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 150, 168), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("MySql Connection");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 430, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 780, 70));

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 150, 168), 8));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel19.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, -1));

        jbtnAddnew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnAddnew.setText("ADD NEW");
        jbtnAddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddnewActionPerformed(evt);
            }
        });
        jPanel19.add(jbtnAddnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, -1));

        jbtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnUpdate.setText("UPDATE DATA");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel19.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPrint.setText("PRINT");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel19.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, -1));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnReset.setText("RESET");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel19.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, -1));

        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel19.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, -1));

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 190, 380));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 150, 168), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Student ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        jtxtStudentid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jtxtStudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 16, 360, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("First Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        jtxtFirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jtxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 46, 360, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Address");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Surname");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, -1));

        jtxtAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 106, 360, 30));

        jtxtSurname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 76, 360, 30));

        jtxtTelephone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jtxtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 166, 360, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Telephone");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 20));

        jtxtPostcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtxtPostcode.setText("PostCode");
        jPanel2.add(jtxtPostcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 20));

        jtxtPostCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 136, 360, 30));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 0, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "StudentID", "FirstName", "Surname", "Address", "PostCode", "Telephone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 580, 170));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 600, 380));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setText("MySql Connection");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 430, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 780, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
       MessageFormat header = new MessageFormat("Printing in Progress");
       MessageFormat footer = new MessageFormat("Page {0,number,integer}");
       try
       {
           jTable1.print(JTable.PrintMode.NORMAL,header,footer);
       }
       catch(java.awt.print.PrinterException e)
               {
                   System.err.format("No Printer found", e.getMessage());
               }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtStudentid.setText("");
        jtxtFirstName.setText("");
        jtxtSurname.setText("");
        jtxtAddress.setText("");
        jtxtPostCode.setText("");
        jtxtTelephone.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed
   private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","MYSQL connector",
                JOption.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnAddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddnewActionPerformed
       
         try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataconn,username,password);
            pst = sqlConn.prepareStatement("insert into connector(Studentid,FirstName,Surname,Address,PostCode,Telephone)value(?,?,?,?,?,?)");
            
            pst.setString(1, jtxtStudentid.getText());
            pst.setString(2, jtxtFirstName.getText());
            pst.setString(3, jtxtSurname.getText());
            pst.setString(4, jtxtAddress.getText());
            pst.setString(5, jtxtPostCode.getText());
            pst.setString(6, jtxtTelephone.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            upDateDB(); 
        }
         catch(ClassNotFoundException ex)
         {
             java.util.logging.Logger.getLogger(Mava_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
         }catch(SQLException ex)
                     {
                        java.util.logging.Logger.getLogger(Mava_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                     }
    }//GEN-LAST:event_jbtnAddnewActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
         try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataconn,username,password);
            pst = sqlConn.prepareStatement("update connector set Studentid = ?,Firstname = ?,Surname = ?,Address = ?,PostCode = ?,Telephone = ? where id = ?");
            
            pst.setString(1, jtxtStudentid.getText());
            pst.setString(2, jtxtFirstName.getText());
            pst.setString(3, jtxtSurname.getText());
            pst.setString(4, jtxtAddress.getText());
            pst.setString(5, jtxtPostCode.getText());
            pst.setString(6, jtxtTelephone.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            upDateDB(); 
        }
         catch(ClassNotFoundException ex)
         {
             java.util.logging.Logger.getLogger(Mava_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
         }catch(SQLException ex)
                     {
                        java.util.logging.Logger.getLogger(Mava_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                     }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
       int SelectedRows = jTable1.getSelectedRow();
       
       jtxtStudentid.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
       jtxtFirstName.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
       jtxtSurname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
       jtxtAddress.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
       jtxtPostCode.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
       jtxtTelephone.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
       DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
       int SelectedRows = jTable1.getSelectedRow();
       
       try
       {
           id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
           deleteItem = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete item","Warning",JOptionPane.YES_NO_OPTION);
           if(deleteItem == JOptionPane.YES_OPTION)
           {
               Class.forName("com.mysql.cj.jdbc.Driver");
               sqlConn = DriverManager.getConnection(dataconn,username,password);
               pst = sqlConn.prepareStatement("delete from connector where id = ?");
               
               pst.setInt(1, id);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(this, "Record updated");
               upDateDB();
               
               jtxtStudentid.setText("");
               jtxtFirstName.setText("");
               jtxtSurname.setText("");
               jtxtAddress.setText("");
               jtxtPostCode.setText("");
               jtxtTelephone.setText("");
               
           }
       }
       catch(ClassNotFoundException ex)
       {
           java.util.logging.Logger.getLogger(Mava_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
       catch(SQLException ex)
       {
           System.err.println(ex);
       }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mava_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mava_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mava_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mava_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mava_MysqlConn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAddnew;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JLabel jtxtPostcode;
    private javax.swing.JTextField jtxtStudentid;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTelephone;
    // End of variables declaration//GEN-END:variables
}
